# lgtm.com delivers security scans
# We need to setup a tailor-made extraction configuration, because we require e.g. libpmem2 >= 1.10,
# cmake >= 3.16, and they are not available in Ubuntu 19.10 (which is currently used in lgtm builds).
extraction:
  cpp:
    prepare:
      packages:
        - libdaxctl-dev
        - libndctl-dev
        - pandoc
    after_prepare:
      - wget -O install-cmake.sh https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.sh
      - chmod +x ./install-cmake.sh
      - mkdir $LGTM_WORKSPACE/installed/
      - ./install-cmake.sh --skip-license --prefix=$LGTM_WORKSPACE/installed/
      - export PATH=$LGTM_WORKSPACE/installed/bin:$PATH
      - git clone https://github.com/pmem/pmdk
      - cd pmdk
      - make install -j$(nproc) prefix=$LGTM_WORKSPACE/installed/
      - export PKG_CONFIG_PATH=$LGTM_WORKSPACE/installed/lib/pkgconfig:$PKG_CONFIG_PATH
      - cd ..
      - git clone https://github.com/pmem/miniasync
      - cd miniasync && mkdir build && cd build
      - git checkout 8222c233addc20c9938691ba44b905c4a5f58e39
      - cmake .. -DCMAKE_INSTALL_PREFIX=$LGTM_WORKSPACE/installed/
      - make -j$(nproc) install
    index:
      build_command:
        - mkdir build
        - cd build
        - cmake .. -DTESTS_RAPIDCHECK=OFF
        - make -j$(nproc)
